#!/bin/sh

set -eu

VERSION=$(dpkg-parsechangelog | sed -rne 's,^Version: (.+)-.*,\1,p')
SRC=/usr/src/vizzini-$VERSION

cat <<EOF
Makefile      $SRC
vizzini.c     $SRC
vizzini.h     $SRC
vzioctl.h     $SRC
EOF
